# Generated by Django 4.1.3 on 2022-11-09 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botella', '0001_initial'),
        ('garrafon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('botella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botella.botella')),
                ('garrafon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garrafon.garrafon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
