# Generated by Django 4.1.3 on 2022-11-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_usergoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoals',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
