# Generated by Django 4.1.3 on 2022-11-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garrafon', '0002_garrafon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='garrafon',
            name='code',
            field=models.CharField(default='code123', max_length=20),
        ),
    ]
