# Generated by Django 4.1.3 on 2022-11-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garrafon', '0003_garrafon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='garrafon',
            name='refills',
            field=models.IntegerField(default=0),
        ),
    ]
